apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260625-190216-8zdnne94arn3-service
spec:
  selector:
    app: enterprise-system-20260625-190216-8zdnne94arn3
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
